# Generated by Django 6.0.4 on 2026-06-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="payment_mode",
            field=models.CharField(default="Cash", max_length=40),
        ),
    ]
