# Generated by Django 6.0.4 on 2026-06-02 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_bill_payment_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="customer_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["-created_at"], name="billing_bil_created_0df0b9_idx"
            ),
        ),
    ]
