# Generated by Django 6.0.4 on 2026-06-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tenants",
            field=models.ManyToManyField(
                blank=True,
                help_text="The tenants this user belongs to.",
                related_name="user_set",
                to="tenants.tenant",
                verbose_name="tenants",
            ),
        ),
    ]
