# Generated by Django 6.0.4 on 2026-06-01 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In stock"),
                            ("sold", "Sold"),
                            ("removed", "Removed"),
                        ],
                        default="in_stock",
                        max_length=10,
                    ),
                ),
                (
                    "batch",
                    models.UUIDField(
                        db_index=True, help_text="Groups units added together"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.RemoveField(model_name="stockmovement", name="product",),
        migrations.RemoveConstraint(model_name="product", name="unique_sku_per_shop",),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, help_text="Optional manufacturer code", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_items",
                to="inventory.product",
            ),
        ),
        migrations.DeleteModel(name="StockMovement",),
        migrations.RemoveField(model_name="product", name="stock_quantity",),
    ]
