# Generated by Django 6.0.4 on 2026-06-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockitem_remove_stockmovement_product_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="inventory_p_name_f6a6a1_idx"),
        ),
        migrations.AddIndex(
            model_name="seller",
            index=models.Index(fields=["name"], name="inventory_s_name_88cce0_idx"),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(
                fields=["product", "status"], name="inventory_s_product_ec5d3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(
                fields=["-created_at"], name="inventory_s_created_1acde0_idx"
            ),
        ),
    ]
