# Generated by Django 6.0.4 on 2026-06-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["name"], name="customers_c_name_f018e2_idx"),
        ),
    ]
